  export default  { lines: [
"<span><p><h2>Vedtægter for Fritidsforeningen Sport &amp; Kultur i Sydhavnen</h2><br /><strong>Foreningsnummer 28292</strong>",
"<p><strong>§1: Foreningens navn og hjemsted</strong></p>",
"<p>Foreningens navn er Børnefritidsforeningen i Sydhavnen</p>",
"<p>Foreningens hjemsted er København.</p>",
"<p><strong>§2: Foreningens formål</strong></p>",
"<p>Foreningens formål er at støtte fælles fritidsaktiviteter for børn i Sydhavnen i samarbejde med deres familier og det omgivende miljø og samfund. Fritidsaktiviteter kan være sportslige, kulturelle, musiske og/eller sociale aktiviteter men er ikke begrænset hertil. Fælles er, at aktiviteterne skal være med til at styrke fællesskabet i dagligdagen i det omgivende nærmiljø i Sydhavnen for børn i institutionsalderen, skolealderen og deres familier.</p>",
"<p><strong>§3: Tegning af foreningen</strong></p>",
"<p>Foreningen tegnes af formand og kasserer i forening, eller af en af de to i forening med et af de øvrige bestyrelsesmedlemmer. Foreningen kan godkende, at formand og kasserer kan råde over dankort/netbank med foreningens bankkonto hver for sig.</p>",
"<p>Ved beløb under 1.000,- kr. kan kassereren alene underskrive.</p>",
"<p><strong>§4: Samarbejdspartnere</strong></p>",
"<p>Foreningen samarbejder med Skolen i Sydhavnen og øvrige skoler i Sydhavnen, idrætsforeninger, musikforeninger og -skoler, erhvervsvirksomheder og andre relevante samarbejdspartnere.</p>",
"<p><strong>§5: Foreningens medlemmer</strong></p>",
"<p>Medlemmer kan være børn fra Sydhavnen, i aldersgruppen fra vuggestue til 10. klasse, samt personale på skolerne og institutionerne i Sydhavnen. Børn repræsenteres på generalforsamlingen af deres forældre eller værge. I familier med flere børn, skal hvert indmeldt barn have sit eget medlemsnummer.</p>",
"<p><strong>§6: Kontingent</strong></p>",
"<p>Foreningens kontingent fastsættes før hver sæson af bestyrelsen og godkendes på generalforsamlingen.</p>",
"<p>375,- kr. pr. aktivitet pr. barn er fastsat (i visse tilfælde kan kontingent for en aktivitet dog sættes højere, dersom omkostningerne forbundet med aktiviteten kræver dette, eller lavere i tilfælde af, at aktiviteten ikke varer en hel sæson).</p>",
"<p>100,- kr. i støttekontingent pr. sæson. Kriterierne for at blive støttemedlem er de samme som kriterierne for at blive medlem. Støttemedlemsskabet kan fx benyttes, hvis man gerne vil bevare sit medlemskab gennem en sæson, hvor man ikke deltager i aktiviteter.</p>",
"<p>En sæson løber fra september til og med april. Kontingent opkræves forud for hver sæson. Kontingent samt tilslutning til foreningens formål er en betingelse for medlemskab og deltagelse i aktiviteter i foreningens regi.</p>",
"<p><strong>§7: Bestyrelse</strong></p>",
"<p>Foreningens bestyrelse består af 5 medlemmer, samt op til 5 suppleanter, der vælges på den ordinære generalforsamling.</p>",
"<p>Bestyrelsen konstituerer sig selv med formand, næstformand og kasserer og fastsætter selv sin forretningsorden.</p>",
"<p>Bestyrelsesmedlemmer vælges for 2 år ad gangen, således at 3 af medlemmerne er på valg i ulige år, mens 2 af medlemmerne er på valg i lige år. I foreningens første leveår vælges 2 af bestyrelsesmedlemmerne således kun for et år, da de allerede i foråret 2014 vil være på valg igen. Suppleanter vælges for et år ad gangen.</p>",
"<p>I tilfælde af stemmelighed i bestyrelsen er formandens stemme udslagsgivende.</p>",
"<p>Bestyrelsen indkaldes som udgangspunkt skriftligt med minimum 8 dages varsel af formanden og er beslutningsdygtig, såfremt halvdelen af bestyrelsen er mødt. Der indkaldes til bestyrelsesmøde min. 2 gange om året. Bestyrelsessuppleanter kan deltage uden stemmeret.</p>",
"<p>Bestyrelsen kan nedsætte arbejdsgrupper mm.</p>",
"<p><strong>§8: Generalforsamlingen</strong></p>",
"<p> 1. Generalforsamlingen er foreningens højeste myndighed i alle anliggender. Generalforsamlingen er til enhver tid beslutningsdygtig.</p>",
"<p>2. Den ordinære generalforsamling afholdes hvert år i marts og skal indkaldes med min. 2 ugers varsel. Indkaldelsen skal indeholde generalforsamlingens dagsorden.</p>",
"<p>Forslag, der ønskes behandlet på generalforsamlingen, skal være bestyrelsen i hænde senest 1 uge før generalforsamlingen.</p>",
"<p>3.  Dagsorden for ordinær generalforsamling</p>",
"<p>a. Dagsorden for den ordinære generalforsamling skal indeholde minimum følgende punkter:</p>",
"<p>b. Valg af dirigent</p>",
"<p>c. Valg af referent</p>",
"<p>d. Årsberetning samt godkendelse heraf</p>",
"<p>e. Fremlæggelse af regnskab, budget og kontingent</p>",
"<p>f. Behandling af indkomne forslag (skal være indkommet senest 1 uge før generalforsamlingen)</p>",
"<p>g. Valg af bestyrelse og 1 bestyrelsessuppleant</p>",
"<p>h. Valg af revisor og revisorsuppleant</p>",
"<p>i. Eventuelt</p>",
"<p>4. Stemmeret på generalforsamlingen har (forældre til) alle medlemmer, der har betalt kontingent. Medlemmer (eller forældre til medlemmer), der på baggrund af en bestyrelsesbeslutning er fritaget fra kontingent, har også stemmeret. En stemme pr. barn.</p>",
"<p>Alle beslutninger på en generalforsamling træffes ved almindeligt stemmeflertal ved håndsoprækning (dog med skriftlig afstemning såfremt mindst 1 medlem af foreningen kræver det), med undtagelse af beslutning om foreningens opløsning, mere herom i §13.</p>",
"<p><strong>§9: Ekstraordinær generalforsamling</strong></p>",
"<p>Ekstraordinær generalforsamling kan til enhver tid indkaldes af bestyrelsen og skal indkaldes, når mindst 1/3 af foreningens medlemmer skriftligt indgiver begæring herom til bestyrelsen.</p>",
"<p>I sidstnævnte tilfælde skal generalforsamlingen afholdes senest 1 måned efter, at begæringen er fremsat. Indkaldelse skal indeholde alle relevante oplysninger om det emne, som ønskes behandlet og den ekstraordinære generalforsamling skal kun behandle dette emne.</p>",
"<p>Indkaldelsen skal ske på samme måde som den ordinære generalforsamling.</p>",
"<p><strong>§10: Regnskab</strong></p>",
"<p>Foreningens regnskabsår følger kalenderåret.</p>",
"<p><strong>§11: Revision</strong></p>",
"<p>Det reviderede regnskab med kommende års budget skal være fremsendt til medlemmerne senest 14 dage før den ordinære generalforsamling.</p>",
"<p>Revision finder sted en gang årligt efter regnskabsårets afslutning. Uanmeldt kasseeftersyn kan finde sted, når revisoren ønsker det.</p>",
"<p>Foreningen hæfter kun for sine forpligtelser med den af foreningen til enhver tid hørende formue. Der påhviler ikke foreningens medlemmer eller bestyrelsen nogen personlig hæftelse.</p>",
"<p><strong>§12: Vedtægtsændringer</strong></p>",
"<p>Ændringer af disse vedtægter kan kun ske på foreningens generalforsamling.</p>",
"<p><strong>§13: Foreningens opløsning</strong></p>",
"<p>Bestemmelse om foreningens opløsning kræver et flertal på 2/3 af generalforsamlingens eller den ekstraordinære generalforsamlings fremmødte medlemmer.</p>",
"<p>Opløsningen skal herefter godkendes på en efterfølgende ny ekstraordinær generalforsamling med samme formål, hvor beslutning kan opnås med ovennævnte stemmeflertal, uanset hvor mange af foreningens medlemmer, der er fremmødt.</p>",
"<p>Foreningens aktiver skal ved opløsning overføres til almennyttige formål, først og fremmest ved Skolen i Sydhavnen, hvis en forening, organisation eller fond eksisterer, som støtter lign. formål.</p>",
"<p> </p>",
"<p>Vedtaget på ordinær generalforsamling den 27. marts 2014</p></span><span></span>"
  ]};